
platform :ios, "8.0"

use_frameworks!
inhibit_all_warnings!

target 'SwiftDemo' do
    
pod 'SnapKit', '~> 0.22.0'
pod 'Kingfisher', '~> 2.4.3'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'Alamofire', '~> 3.4.1'
pod 'SwiftyJSON', '~> 2.3.2'
pod 'QorumLogs', '~> 0.8'

end

